version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mcat-tracker-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcat_tracker
    volumes:
      - mcat_tracker_data:/var/lib/postgresql/data

volumes:
  mcat_tracker_data:
    driver: local 